"""empty message

Revision ID: 19debfc21357
Revises: 3896284d19c6
Create Date: 2021-01-07 12:54:42.068290

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '19debfc21357'
down_revision = '3896284d19c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productvarianttype',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvarianttype_id'), 'productvarianttype', ['id'], unique=True)
    op.create_table('productvarianttypeoption',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('variant_type_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('option', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['variant_type_id'], ['productvarianttype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productvarianttypeoption_id'), 'productvarianttypeoption', ['id'], unique=True)
    op.create_table('productvariant',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prd_seller_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('regular_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('max_order_quantity', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), nullable=False),
    sa.Column('product_variant_option_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['prd_seller_id'], ['prdstore.id'], ),
    sa.ForeignKeyConstraint(['product_variant_option_id'], ['productvarianttypeoption.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_variant_option_id')
    )
    op.create_index(op.f('ix_productvariant_id'), 'productvariant', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_productvariant_id'), table_name='productvariant')
    op.drop_table('productvariant')
    op.drop_index(op.f('ix_productvarianttypeoption_id'), table_name='productvarianttypeoption')
    op.drop_table('productvarianttypeoption')
    op.drop_index(op.f('ix_productvarianttype_id'), table_name='productvarianttype')
    op.drop_table('productvarianttype')
    # ### end Alembic commands ###
