"""empty message

Revision ID: 2fb5a6f2311b
Revises: ccf4aa6d31b2
Create Date: 2021-01-06 16:52:46.193271

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2fb5a6f2311b'
down_revision = 'ccf4aa6d31b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buyer',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buyer_id'), 'buyer', ['id'], unique=True)
    op.add_column('cart', sa.Column('buyer_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.drop_constraint('cart_user_id_fkey', 'cart', type_='foreignkey')
    op.create_foreign_key(None, 'cart', 'buyer', ['buyer_id'], ['id'])
    op.drop_column('cart', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.create_foreign_key('cart_user_id_fkey', 'cart', 'user', ['user_id'], ['id'])
    op.drop_column('cart', 'buyer_id')
    op.drop_index(op.f('ix_buyer_id'), table_name='buyer')
    op.drop_table('buyer')
    # ### end Alembic commands ###
