"""empty message

Revision ID: 36b3fbf467ad
Revises: 3dde17d14664
Create Date: 2021-01-05 10:54:36.523466

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36b3fbf467ad'
down_revision = '3dde17d14664'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productprice',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productprice_id'), 'productprice', ['id'], unique=True)
    op.create_table('productcoupon',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('prd_seller_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('coupon_code', sa.String(), nullable=True),
    sa.Column('expiry_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('discount_type', sa.Enum('price', 'quantity', name='coupontype'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prd_seller_id'], ['prdseller.id'], ),
    sa.PrimaryKeyConstraint('id', 'prd_seller_id'),
    sa.UniqueConstraint('coupon_code')
    )
    op.create_index(op.f('ix_productcoupon_id'), 'productcoupon', ['id'], unique=True)
    op.add_column('prdseller', sa.Column('price_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'prdseller', 'productprice', ['price_id'], ['id'])
    op.drop_column('prdseller', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prdseller', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prdseller', type_='foreignkey')
    op.drop_column('prdseller', 'price_id')
    op.drop_index(op.f('ix_productcoupon_id'), table_name='productcoupon')
    op.drop_table('productcoupon')
    op.drop_index(op.f('ix_productprice_id'), table_name='productprice')
    op.drop_table('productprice')
    # ### end Alembic commands ###
