"""empty message

Revision ID: 585a4e7927af
Revises: 406db25b406c
Create Date: 2021-01-07 19:56:26.274446

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '585a4e7927af'
down_revision = '406db25b406c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller', sa.Column('buisness_address_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('seller', sa.Column('buisness_name', sa.String(), nullable=False))
    op.add_column('seller', sa.Column('name_on_income_tax', sa.String(), nullable=False))
    op.add_column('seller', sa.Column('tax_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'seller', 'address', ['buisness_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seller', type_='foreignkey')
    op.drop_column('seller', 'tax_id')
    op.drop_column('seller', 'name_on_income_tax')
    op.drop_column('seller', 'buisness_name')
    op.drop_column('seller', 'buisness_address_id')
    # ### end Alembic commands ###
