"""empty message

Revision ID: b5be99f8014e
Revises: 19debfc21357
Create Date: 2021-01-07 13:06:07.878857

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b5be99f8014e'
down_revision = '19debfc21357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productvariantoptionmap',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('product_variant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('product_variant_option_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['product_variant_id'], ['productvariant.id'], ),
    sa.ForeignKeyConstraint(['product_variant_option_id'], ['productvarianttypeoption.id'], ),
    sa.PrimaryKeyConstraint('id', 'product_variant_option_id')
    )
    op.create_index(op.f('ix_productvariantoptionmap_id'), 'productvariantoptionmap', ['id'], unique=True)
    op.drop_constraint('productvariant_product_variant_option_id_fkey', 'productvariant', type_='foreignkey')
    op.drop_column('productvariant', 'product_variant_option_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productvariant', sa.Column('product_variant_option_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('productvariant_product_variant_option_id_fkey', 'productvariant', 'productvarianttypeoption', ['product_variant_option_id'], ['id'])
    op.drop_index(op.f('ix_productvariantoptionmap_id'), table_name='productvariantoptionmap')
    op.drop_table('productvariantoptionmap')
    # ### end Alembic commands ###
