"""empty message

Revision ID: d40265b5b25a
Revises: 36b3fbf467ad
Create Date: 2021-01-05 22:20:08.944610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd40265b5b25a'
down_revision = '36b3fbf467ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productprice', sa.Column('actual_price', sa.Float(), nullable=True))
    op.add_column('productprice', sa.Column('discounted_price', sa.Float(), nullable=True))
    op.add_column('productprice', sa.Column('shipping_charges', sa.Float(), nullable=True))
    op.drop_column('productprice', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productprice', sa.Column('price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('productprice', 'shipping_charges')
    op.drop_column('productprice', 'discounted_price')
    op.drop_column('productprice', 'actual_price')
    # ### end Alembic commands ###
